//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucaSystem {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LucaSystem.GameCode", typeof(GameCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 EQU
        ///EQUN
        ///EQUV
        ///ADD
        ///SUB
        ///MUL
        ///DIV
        ///MOD
        ///AND
        ///OR
        ///RANDOM
        ///VARSTR
        ///VARSTR_ADD
        ///SET
        ///FLAGCLR
        ///GOTO
        ///ONGOTO
        ///GOSUB
        ///IFY
        ///IFN
        ///RETURN
        ///JUMP
        ///FARCALL
        ///FARRETURN
        ///JUMPPOINT
        ///END
        ///VARSTR_SET
        ///VARSTR_ALLOC
        ///TALKNAME_SET
        ///ARFLAGSET
        ///COLORBG_SET
        ///SPLINE_SET
        ///SHAKELIST_SET
        ///MESSAGE
        ///MESSAGE_CLEAR
        ///MESSAGE_WAIT
        ///SELECT
        ///CLOSE_WINDOW
        ///LOG
        ///LOG_PAUSE
        ///LOG_END
        ///VOICE
        ///WAIT_COUNT
        ///WAIT_TIME
        ///FFSTOP
        ///INIT
        ///STOP
        ///IMAGELOAD
        ///IMAGEUPADTE
        ///ARC
        ///MOVE
        ///MOVE2
        ///ROT
        ///PEND
        ///FADE
        ///SCALE
        ///SHAKE
        ///SHAKELIST
        ///BASE
        ///MCMOVE
        ///MCARC
        ///MCROT
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EQU
        ///EQUN
        ///EQUV
        ///ADD
        ///SUB
        ///RANDOM
        ///VARSTR
        ///SET
        ///GOTO
        ///ONGOTO
        ///GOSUB
        ///IFY
        ///IFN
        ///RETURN
        ///JUMP
        ///FARCALL
        ///FARRETURN
        ///END
        ///VARSTR_SET
        ///TALKNAME_SET
        ///ARFLAGSET
        ///COLORBG_SET
        ///SPLINE_SET
        ///QUAKE_SET
        ///MESSAGE
        ///MESSAGE_CLEAR
        ///SELECT
        ///CLOSE_WINDOW
        ///LOG
        ///LOG_PAUSE
        ///LOG_END
        ///WAIT_COUNT
        ///WAIT_TIME
        ///FFSTOP
        ///INIT
        ///STOP
        ///IMAGELOAD
        ///ARC
        ///MOVE
        ///MOVE2
        ///ROT
        ///PEND
        ///FADE
        ///SCALE
        ///SHAKE
        ///QUAKE
        ///BASE
        ///MCMOVE
        ///MCARC
        ///MCROT
        ///MCSHAKE
        ///MCFADE
        ///WAIT
        ///DRAW
        ///WIPE
        ///FRAMEON
        ///FRAMEOFF
        ///FW
        ///CLIP
        ///DELAY
        ///RASTER
        ///TONE
        ///SCALECOSSIN
        ///BMODE
        ///SIZE
        ///SPLINE
        ///DISP
        ///SG_QUAKE
        ///PLAYMUSIC
        ///PLAYMUSIC_WAITSTART
        ///PLAYSE
        ///STOPSE
        ///V [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ISLAND {
            get {
                return ResourceManager.GetString("ISLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EQU
        ///EQUN
        ///EQUV
        ///ADD
        ///SUB
        ///MUL
        ///DIV
        ///MOD
        ///AND
        ///OR
        ///RANDOM
        ///VARSTR
        ///VARSTR_ADD
        ///SET
        ///FLAGCLR
        ///GOTO
        ///ONGOTO
        ///GOSUB
        ///IFY
        ///IFN
        ///RETURN
        ///JUMP
        ///FARCALL
        ///FARRETURN
        ///JUMPPOINT
        ///END
        ///VARSTR_SET
        ///VARSTR_ALLOC
        ///TALKNAME_SET
        ///ARFLAGSET
        ///COLORBG_SET
        ///SPLINE_SET
        ///SHAKELIST_SET
        ///SCISSOR_TRIANGLELIST_SET
        ///MESSAGE
        ///MESSAGE_CLEAR
        ///MESSAGE_WAIT
        ///SELECT
        ///CLOSE_WINDOW
        ///LOG
        ///LOG_PAUSE
        ///LOG_END
        ///VOICE
        ///WAIT_COUNT
        ///WAIT_TIME
        ///WAIT_TEXTFEED
        ///FFSTOP
        ///INIT
        ///STOP
        ///IMAGELOAD
        ///IMAGEUPADTE
        ///ARC
        ///MOVE
        ///MOVE2
        ///ROT
        ///PEND
        ///FADE
        ///SCALE
        ///SHAKE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SP {
            get {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }
    }
}
